// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXA-0n5EGO6ST5quk2xNPRGwMQmoZyVNo',
    appId: '1:892741031223:android:7929d6a5ec65c6649176b2',
    messagingSenderId: '892741031223',
    projectId: 'angulartest-55eea',
    databaseURL: 'https://angulartest-55eea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'angulartest-55eea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx9e2Bq7_urq-lv5F7uoltpTIJJSSh2og',
    appId: '1:892741031223:ios:3d7053da4e1c3a079176b2',
    messagingSenderId: '892741031223',
    projectId: 'angulartest-55eea',
    databaseURL: 'https://angulartest-55eea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'angulartest-55eea.appspot.com',
    iosClientId: '892741031223-vjmulk1o9kppn8pj2v058g0po9icdakd.apps.googleusercontent.com',
    iosBundleId: 'com.pintapontus.myFirstApp',
  );
}
